"""
LLM Service - Real AI API integration for text simplification, chat, and FAQs.

Every call builds its prompt from the ACTUAL user request (never a canned
response). Providers are tried in order via services.ai_service:
Gemini -> OpenAI-compatible API -> extractive offline fallback.
"""

import os
from typing import List, Dict, Optional

from services import ai_service

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")


def is_available() -> bool:
    """True if at least one real LLM provider (Gemini/OpenAI-compatible) is configured."""
    return ai_service.ai_available()


def _fallback_simplify(text: str) -> str:
    """Offline fallback used when no AI provider is available."""
    sentences = [s.strip() for s in text.replace("\n", " ").split(".") if s.strip()]
    bullets = "\n".join(f"- {s}" for s in sentences[:10])
    return (
        "⚠️ AI simplification is offline (no GEMINI_API_KEY / OPENAI_API_KEY configured). "
        "Here is a plain breakdown of the key points:\n\n" + (bullets or text)
    )


def simplify_text(text: str, level: str = "10-year-old") -> str:
    """
    Simplify complex text to a given reading level using a live AI API.

    Args:
        text: The complex text to simplify
        level: Target reading level (default: "10-year-old")

    Returns:
        Simplified text generated by the AI for THIS specific text.
    """
    result = ai_service.generate(ai_service.simplify_prompt(text, level))
    if result:
        return result
    return _fallback_simplify(text)


def chat_with_document(document_text: str, question: str,
                       history: Optional[List[Dict[str, str]]] = None) -> str:
    """
    Answer a specific question about a document using a live AI API.

    Args:
        document_text: The document content
        question: The user's actual question (drives the response)
        history: Optional prior conversation turns [{role, content}]

    Returns:
        An answer generated for THIS specific question.
    """
    result = ai_service.generate(
        ai_service.chat_prompt(document_text, question, history)
    )
    if result:
        return result
    # No API configured/working: give a question-specific extractive answer
    # instead of a single canned reply.
    return ai_service._extractive_answer(document_text, question)


def generate_faqs(scheme) -> List[Dict[str, str]]:
    """
    Generate FAQs for a scheme using Gemini.
    
    Args:
        scheme: Scheme object with details
    
    Returns:
        List of FAQ dictionaries with 'question' and 'answer' keys
    """
    def _default_faqs():
        return [
            {"question": "How to apply?", "answer": f"Visit the official website or nearest CSC center. {(scheme.application_process or '')[:200]}"},
            {"question": "What documents are needed?", "answer": scheme.documents_required or "Please check the official website for document requirements."},
        ]

    if not ai_service.ai_available():
        return _default_faqs()

    prompt = f"""Generate 5 frequently asked questions (FAQs) about this government scheme.
Each FAQ should have a question and a clear, helpful answer.
Focus on common concerns like eligibility, documents needed, how to apply, timelines, etc.

SCHEME NAME: {scheme.scheme_name}
STATE: {scheme.state}
CATEGORY: {scheme.category}
ELIGIBILITY: {scheme.eligibility}
BENEFITS: {scheme.benefits}
APPLICATION PROCESS: {scheme.application_process}

Format your response as:
Q1: [question]
A1: [answer]
Q2: [question]
A2: [answer]
...and so on for 5 FAQs."""

    text = ai_service.generate(prompt)
    if not text:
        return _default_faqs()

    try:
        # Parse FAQs
        faqs = []
        lines = text.strip().split('\n')
        current_q = None
        current_a = None
        
        for line in lines:
            line = line.strip()
            if line.startswith('Q') and ':' in line:
                if current_q and current_a:
                    faqs.append({"question": current_q, "answer": current_a})
                current_q = line.split(':', 1)[1].strip()
                current_a = None
            elif line.startswith('A') and ':' in line:
                current_a = line.split(':', 1)[1].strip()
            elif current_a is not None and line:
                current_a += " " + line
        
        if current_q and current_a:
            faqs.append({"question": current_q, "answer": current_a})
        
        return faqs[:5]
    except Exception as e:
        print(f"Gemini FAQ generation error: {e}")
        return _default_faqs()
